Added discount on all wooden beads (-20%) and decorative pins (-10%).
KanarekLife/PasmanteriaFryderyka pull request #23
Opened 2024-11-26 14:34 UTC by oenea

Discount visible in the basket. Added product combinations of all products with decorative pins (4 pcs) and wooden beads (4 pcs). The price change is visible only in the basket (is it supposed to be like that? Is it a bug?).

2024-11-26 19:09 UTC, KanarekLife approved these changes
lgtm

2024-11-27 13:49 UTC, Nasus20202 commented
It would be nice to add discounted and out of stock product links to the README.

2024-11-28 21:48 UTC, Nasus20202 requested changes

2024-11-28 21:48 UTC, Nasus20202 commented on src/README.md
> +6. Discount and out of stock products.
Please replace this with a new section header.

2024-11-28 22:06 UTC, Nasus20202 approved these changes

2024-11-29 10:22 UTC, merged